import React, { useState, useEffect } from 'react';
import { AppMode, Message, SessionReport, HistoryItem } from './types';
import { LiveSession } from './components/LiveSession';
import { Report } from './components/Report';
import { HistoryList } from './components/HistoryList';
import { generateScenarioImage } from './services/geminiService';
import { saveHistoryItem } from './services/historyService';
import { Camera, Mic, Play, Key, History } from 'lucide-react';
import { LoadingSpinner } from './components/LoadingSpinner';

function App() {
  const [appMode, setAppMode] = useState<AppMode>(AppMode.IDLE);
  const [topic, setTopic] = useState('');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [sessionMessages, setSessionMessages] = useState<Message[]>([]);
  const [hasApiKey, setHasApiKey] = useState(false);
  const [isCheckingKey, setIsCheckingKey] = useState(true);
  
  // State for viewing History
  const [viewingHistoryReport, setViewingHistoryReport] = useState<SessionReport | null>(null);

  useEffect(() => {
    const checkKey = async () => {
      const aistudio = (window as any).aistudio;
      if (aistudio && typeof aistudio.hasSelectedApiKey === 'function') {
        try {
            const hasKey = await aistudio.hasSelectedApiKey();
            setHasApiKey(hasKey);
        } catch (e) {
            console.error("Error checking API key:", e);
            setHasApiKey(false);
        }
      } else {
        // Fallback if not in AI Studio env
        setHasApiKey(true);
      }
      setIsCheckingKey(false);
    };
    checkKey();
  }, []);

  const handleSelectKey = async () => {
    const aistudio = (window as any).aistudio;
    if (aistudio && typeof aistudio.openSelectKey === 'function') {
      try {
        await aistudio.openSelectKey();
        const hasKey = await aistudio.hasSelectedApiKey();
        setHasApiKey(hasKey);
      } catch (e) {
        console.error("Error selecting key:", e);
        setHasApiKey(true); 
      }
    }
  };

  const handleStartScenario = async () => {
    if (!topic) return;
    setViewingHistoryReport(null);
    setAppMode(AppMode.SCENARIO_SETUP);
    try {
      const imageBase64 = await generateScenarioImage(topic);
      setGeneratedImage(imageBase64);
      setAppMode(AppMode.SCENARIO_LIVE);
    } catch (e) {
      console.error(e);
      alert("Failed to prepare scenario. Please try again.");
      setAppMode(AppMode.IDLE);
    }
  };

  const handleStartInterview = () => {
    if (!topic) return;
    setViewingHistoryReport(null);
    setGeneratedImage(null);
    setAppMode(AppMode.INTERVIEW_LIVE);
  };

  const handleSessionEnd = (msgs: Message[]) => {
    setSessionMessages(msgs);
    setAppMode(AppMode.REPORT);
  };

  // Called when a NEW report is successfully generated by the Report component
  const handleNewReportGenerated = (report: SessionReport) => {
    const newItem: HistoryItem = {
        id: Date.now().toString(),
        timestamp: Date.now(),
        topic: topic,
        mode: generatedImage ? 'SCENARIO' : 'INTERVIEW',
        messages: sessionMessages,
        report: report
    };
    saveHistoryItem(newItem);
  };

  const handleHistorySelect = (item: HistoryItem) => {
      setTopic(item.topic);
      setSessionMessages(item.messages);
      setGeneratedImage(item.mode === 'SCENARIO' ? 'HISTORY_PLACEHOLDER' : null); // Use placeholder to trigger 'SCENARIO' mode logic in Report
      setViewingHistoryReport(item.report);
      setAppMode(AppMode.REPORT);
  };

  const goHome = () => {
      setAppMode(AppMode.IDLE);
      setTopic('');
      setGeneratedImage(null);
      setSessionMessages([]);
      setViewingHistoryReport(null);
  };

  if (isCheckingKey) {
    return (
      <div className="h-screen bg-gray-900 text-white flex items-center justify-center">
        <LoadingSpinner message="Loading..." />
      </div>
    );
  }

  if (!hasApiKey) {
     return (
         <div className="min-h-screen bg-gray-900 flex flex-col items-center justify-center p-6 font-sans text-white">
             <div className="max-w-md text-center space-y-6">
                 <div className="flex justify-center mb-4">
                    <div className="p-4 bg-yellow-500 rounded-full">
                        <Key size={48} className="text-gray-900" />
                    </div>
                 </div>
                 <h1 className="text-3xl font-bold">Configuração Necessária</h1>
                 <p className="text-gray-300">
                     Para usar os modelos avançados de imagem e voz do FalaBrasil AI, você precisa selecionar uma chave de API.
                 </p>
                 <button 
                    onClick={handleSelectKey}
                    className="w-full py-3 bg-green-600 hover:bg-green-700 rounded-xl font-bold text-lg transition-all shadow-lg"
                 >
                    Selecionar Chave API
                 </button>
             </div>
         </div>
     )
  }

  // Render History List
  if (appMode === AppMode.HISTORY_LIST) {
      return (
          <HistoryList 
            onSelect={handleHistorySelect} 
            onBack={goHome}
          />
      );
  }

  // Render Report
  if (appMode === AppMode.REPORT) {
    return (
      <Report 
        messages={sessionMessages} 
        mode={generatedImage ? 'SCENARIO' : 'INTERVIEW'}
        topic={topic}
        existingReport={viewingHistoryReport}
        onReportGenerated={handleNewReportGenerated}
        onBackHome={goHome} 
      />
    );
  }

  // Render Setup Loading
  if (appMode === AppMode.SCENARIO_SETUP) {
    return (
      <div className="h-screen bg-gray-900 text-white flex items-center justify-center">
        <LoadingSpinner message="Gerando cenário realista..." />
      </div>
    );
  }

  // Render Live Session
  if (appMode === AppMode.SCENARIO_LIVE || appMode === AppMode.INTERVIEW_LIVE) {
    return (
      <LiveSession
        mode={appMode === AppMode.SCENARIO_LIVE ? 'SCENARIO' : 'INTERVIEW'}
        topic={topic}
        imageUrl={generatedImage}
        onSessionEnd={handleSessionEnd}
      />
    );
  }

  // Render Home / Start Screen
  return (
    <div className="min-h-screen bg-gradient-to-br from-green-500 to-blue-600 flex flex-col items-center justify-center p-6 font-sans">
      <div className="bg-white rounded-3xl shadow-2xl p-8 w-full max-w-md space-y-8 relative">
        
        {/* History Button */}
        <button 
            onClick={() => setAppMode(AppMode.HISTORY_LIST)}
            className="absolute top-6 right-6 p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-full transition-colors"
            title="Histórico"
        >
            <History size={24} />
        </button>

        <div className="text-center space-y-2">
          <div className="flex justify-center gap-2 mb-4">
            <div className="w-3 h-3 rounded-full bg-green-500"></div>
            <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
            <div className="w-3 h-3 rounded-full bg-blue-600"></div>
          </div>
          <h1 className="text-3xl font-extrabold text-gray-800">FalaBrasil AI</h1>
          <p className="text-gray-500">Pratique sua conversação em Português agora.</p>
        </div>

        <div className="space-y-4">
          <label className="block text-sm font-medium text-gray-700">
            Sobre o que você quer falar?
          </label>
          <input
            type="text"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="Ex: Mercado, Aeroporto, Entrevista..."
            className="w-full px-4 py-3 rounded-xl border border-gray-300 focus:ring-2 focus:ring-green-500 focus:border-transparent outline-none transition-all"
          />
        </div>

        <div className="grid grid-cols-1 gap-4 pt-4">
          <button
            disabled={!topic}
            onClick={handleStartScenario}
            className="group relative flex items-center justify-between w-full p-4 bg-blue-50 border-2 border-blue-100 hover:border-blue-500 rounded-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <div className="flex items-center gap-4">
              <div className="bg-blue-100 p-3 rounded-full text-blue-600 group-hover:bg-blue-600 group-hover:text-white transition-colors">
                <Camera size={24} />
              </div>
              <div className="text-left">
                <h3 className="font-bold text-gray-800">Descrever Cena</h3>
                <p className="text-xs text-gray-500">IA gera uma imagem e faz perguntas</p>
              </div>
            </div>
            <Play size={20} className="text-gray-300 group-hover:text-blue-600" />
          </button>

          <button
            disabled={!topic}
            onClick={handleStartInterview}
            className="group relative flex items-center justify-between w-full p-4 bg-green-50 border-2 border-green-100 hover:border-green-500 rounded-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <div className="flex items-center gap-4">
              <div className="bg-green-100 p-3 rounded-full text-green-600 group-hover:bg-green-600 group-hover:text-white transition-colors">
                <Mic size={24} />
              </div>
              <div className="text-left">
                <h3 className="font-bold text-gray-800">Simular Entrevista</h3>
                <p className="text-xs text-gray-500">IA age como examinador oficial</p>
              </div>
            </div>
            <Play size={20} className="text-gray-300 group-hover:text-green-600" />
          </button>
        </div>
        
        <p className="text-xs text-center text-gray-400 pt-4">
            *Requer permissão de microfone.
        </p>
      </div>
    </div>
  );
}

export default App;